import NextHead from "next/head";

const Head = ({ title }) => {
  return (
    <NextHead>
      <title>{title}</title>
      {/* <title>{title}</title> */}
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/page-logo.ico" />
      <link
        href="https://fonts.googleapis.com/css2?family=Dongle"
        rel="stylesheet"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Montserrat"
        rel="stylesheet"
      />
    </NextHead>
  );
};

export default Head;
